name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  BuildDebug:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "arm64" ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JRE JAR files
        run: |
          chmod +x gradlew
          mkdir out
          ./gradlew jre_lwjgl3glfw:build

      - name: Build Debug ${{matrix.arch}}
        run: |
          chmod +x gradlew
          ./gradlew ZalithLauncher:assembleDebug -Darch=${{ matrix.arch }}

      - name: Upload Debug ${{matrix.arch}}
        uses: actions/upload-artifact@v4
        with:
          name: ZalithLauncher(Debug) ${{ matrix.arch }}
          path: ZalithLauncher/build/outputs/apk/debug/*
